"""TDS / income-tax + Form 16 + Form 24Q + gratuity records.

Scope
=====
- FY-scoped TaxSlabConfig (slabs for both regimes + standard deduction +
  87A rebate + surcharge bands + cess) stored as JSON for flexibility
  across FYs without schema churn.
- FY-scoped SectionLimitConfig (80C, 80D, 80CCD(1B), HRA metro pct,
  etc.) — also JSON.
- EmployeeTaxDeclaration: per (employee, fy) regime + investments +
  HRA + previous-employer income; with verify lifecycle.
- Form16Record: per (employee, fy). Part B generated by us; Part A
  uploaded from TRACES.
- Form24QExport: per (fy, quarter) generated export with status +
  challan tracking, mirrors Part 1's StatutoryFiling pattern.
- GratuityComputation: snapshot of the formula inputs + result at the
  moment of exit (so finance can audit the historical figure later
  even if the employee's last drawn changes via correction).

Backwards-compatibility contract
================================
Pure additive — no existing table touched. No code outside this module
modifies Employee, payroll, salary_calculator, the revision module, or
the Part-1 statutory module. Generators READ finalized payroll.
"""
from datetime import datetime, date as pydate, timezone
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import (
    Boolean, DateTime, Date, Float, ForeignKey, Integer, String, Text,
    UniqueConstraint, JSON,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base


if TYPE_CHECKING:
    from .user import User
    from .employee import Employee


# ----- constants ----------------------------------------------------


class TaxRegime:
    OLD = "old"
    NEW = "new"


class DeclarationStatus:
    DRAFT = "draft"
    SUBMITTED = "submitted"
    VERIFIED = "verified"
    REJECTED = "rejected"


class Form16Status:
    PENDING_PART_A = "pending_part_a"
    READY = "ready"
    ISSUED = "issued"


class Form24QStatus:
    DRAFT = "draft"
    GENERATED = "generated"
    SUBMITTED = "submitted"
    ACCEPTED = "accepted"
    REJECTED = "rejected"


class GratuityStatus:
    ACCRUED = "accrued"            # not yet payable
    ELIGIBLE = "eligible"          # eligibility met but employee active
    COMPUTED = "computed"           # at exit
    PAID = "paid"


# ----- masters ------------------------------------------------------


class TaxSlabConfig(Base):
    """One row per (FY, regime) pair OR one row per FY with both
    regimes inside `slabs_json`. We use the second shape to keep the
    UI simple: one form, two columns.

    JSON shape:
      {
        "old": [ {"upto": 250000, "rate": 0}, ..., {"upto": null, "rate": 30} ],
        "new": [ {"upto": 300000, "rate": 0}, ..., {"upto": null, "rate": 30} ],
        "surcharge_old": [ {"upto": 5000000, "rate": 0}, ... ],
        "surcharge_new": [ {"upto": 5000000, "rate": 0}, ... ],
      }
    """
    __tablename__ = "tax_slab_config"  # type: ignore[assignment]

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    fy: Mapped[str] = mapped_column(
        String(8), unique=True, nullable=False, index=True,
    )                                  # e.g. "2024-25"
    name: Mapped[str] = mapped_column(String(120), nullable=False)

    slabs_json: Mapped[dict] = mapped_column(JSON, nullable=False)

    # Standard deduction (old / new regime).
    standard_deduction_old: Mapped[float] = mapped_column(
        Float, default=50000.0, nullable=False,
    )
    standard_deduction_new: Mapped[float] = mapped_column(
        Float, default=75000.0, nullable=False,
    )

    # Section 87A rebate caps (the threshold of taxable income below
    # which rebate applies, and the max rebate amount).
    rebate_87a_old_threshold: Mapped[float] = mapped_column(
        Float, default=500000.0, nullable=False,
    )
    rebate_87a_old_max: Mapped[float] = mapped_column(
        Float, default=12500.0, nullable=False,
    )
    rebate_87a_new_threshold: Mapped[float] = mapped_column(
        Float, default=700000.0, nullable=False,
    )
    rebate_87a_new_max: Mapped[float] = mapped_column(
        Float, default=25000.0, nullable=False,
    )

    # Cess (Health + Education): 4% of (tax + surcharge).
    cess_rate: Mapped[float] = mapped_column(
        Float, default=4.0, nullable=False,
    )

    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc), nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc), nullable=False,
    )


class SectionLimitConfig(Base):
    """One row per (FY, section_code). e.g.

      (2024-25, "80C", 150000)
      (2024-25, "80D_self_below_60", 25000)
      (2024-25, "80CCD_1B", 50000)
      (2024-25, "hra_metro_pct", 50.0)
      (2024-25, "hra_non_metro_pct", 40.0)

    Storing as a key/limit table (instead of a hard-coded enum) keeps
    new sections (e.g. 80EEB for EV loans) addable without a schema
    change.
    """
    __tablename__ = "section_limit_config"  # type: ignore[assignment]
    __table_args__ = (
        UniqueConstraint("fy", "section_code", name="uq_section_limit_fy_code"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    fy: Mapped[str] = mapped_column(String(8), index=True, nullable=False)
    section_code: Mapped[str] = mapped_column(String(40), nullable=False)
    limit_amount: Mapped[float] = mapped_column(Float, nullable=False)
    # Some sections (e.g. HRA percentages) are not amounts; we use
    # `is_percentage` so the UI renders the field correctly.
    is_percentage: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False,
    )
    # The regime in which the limit applies; "BOTH" by default.
    applies_to: Mapped[str] = mapped_column(
        String(8), default="BOTH", nullable=False,
    )
    notes: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc), nullable=False,
    )


class GratuityConfig(Base):
    """One row, occasionally updated when the cap moves (e.g. Modi
    govt raised it ₹10L → ₹20L in 2018). FY-scoped so historical
    computations replay correctly.
    """
    __tablename__ = "gratuity_config"  # type: ignore[assignment]

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    effective_from: Mapped[pydate] = mapped_column(
        Date, nullable=False, unique=True, index=True,
    )
    # Statutory ceiling (₹20,00,000 since 29-Mar-2018).
    statutory_cap: Mapped[float] = mapped_column(
        Float, default=2000000.0, nullable=False,
    )
    # Minimum continuous service for eligibility (years). The Act says 5.
    eligibility_years: Mapped[int] = mapped_column(
        Integer, default=5, nullable=False,
    )
    # Days basis: 26 working days/month (the Payment of Gratuity Act
    # formula). Some companies use 30 — make it configurable.
    days_basis: Mapped[int] = mapped_column(
        Integer, default=26, nullable=False,
    )
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc), nullable=False,
    )


# ----- declarations -------------------------------------------------


class EmployeeTaxDeclaration(Base):
    """Per (employee, fy) declaration.

    `declarations_json` shape (free-form, all numeric):
      {
        "80C": 150000,
        "80D": 25000,
        "80CCD_1B": 50000,
        "80E": 0,
        ...
      }
    The amount that actually counts toward exemption is min(declared,
    section_limit) — computed at projection time, not here.
    """
    __tablename__ = "employee_tax_declaration"  # type: ignore[assignment]
    __table_args__ = (
        UniqueConstraint(
            "employee_id", "fy", name="uq_emp_tax_decl_fy",
        ),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    employee_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("employee.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    fy: Mapped[str] = mapped_column(String(8), index=True, nullable=False)

    regime: Mapped[str] = mapped_column(
        String(8), default="new", nullable=False,
    )

    declarations_json: Mapped[dict] = mapped_column(
        JSON, default=dict, nullable=False,
    )

    # HRA inputs.
    monthly_rent_paid: Mapped[float] = mapped_column(
        Float, default=0.0, nullable=False,
    )
    rented_in_metro: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False,
    )
    landlord_pan: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)

    # Other income (e.g. interest income, dividends).
    other_income_annual: Mapped[float] = mapped_column(
        Float, default=0.0, nullable=False,
    )
    # Salary from previous employer in same FY (for joiners mid-year).
    previous_employer_income: Mapped[float] = mapped_column(
        Float, default=0.0, nullable=False,
    )
    previous_employer_tds: Mapped[float] = mapped_column(
        Float, default=0.0, nullable=False,
    )

    status: Mapped[str] = mapped_column(
        String(20), default=DeclarationStatus.DRAFT,
        nullable=False, index=True,
    )
    submitted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    verified_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    verified_by_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("user.id", ondelete="SET NULL"), nullable=True,
    )
    rejection_reason: Mapped[Optional[str]] = mapped_column(
        String(500), nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc), nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc), nullable=False,
    )


# ----- Form 16 ------------------------------------------------------


class Form16Record(Base):
    """One row per (employee, fy). Part B is generated; Part A is
    uploaded from TRACES."""
    __tablename__ = "form16_record"  # type: ignore[assignment]
    __table_args__ = (
        UniqueConstraint("employee_id", "fy", name="uq_form16_emp_fy"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    employee_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("employee.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    fy: Mapped[str] = mapped_column(String(8), index=True, nullable=False)

    reference_number: Mapped[Optional[str]] = mapped_column(
        String(80), unique=True, nullable=True,
    )

    # Generated Part B (PDF) — our output.
    part_b_url: Mapped[Optional[str]] = mapped_column(String(512), nullable=True)
    part_b_data: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    part_b_generated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )

    # TRACES-issued Part A (uploaded by HR).
    part_a_url: Mapped[Optional[str]] = mapped_column(String(512), nullable=True)
    part_a_uploaded_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )

    traces_certificate_number: Mapped[Optional[str]] = mapped_column(
        String(60), nullable=True,
    )

    status: Mapped[str] = mapped_column(
        String(30), default=Form16Status.PENDING_PART_A,
        nullable=False, index=True,
    )
    issued_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    missing_pan_flag: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False,
    )

    generated_by_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("user.id", ondelete="SET NULL"), nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc), nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc), nullable=False,
    )


# ----- Form 24Q -----------------------------------------------------


class Form24QExport(Base):
    """One row per (fy, quarter). Mirrors the StatutoryFiling shape
    (status / file_name / summary / challan) for UI consistency."""
    __tablename__ = "form_24q_export"  # type: ignore[assignment]
    __table_args__ = (
        UniqueConstraint("fy", "quarter", name="uq_24q_fy_quarter"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    fy: Mapped[str] = mapped_column(String(8), index=True, nullable=False)
    quarter: Mapped[int] = mapped_column(Integer, nullable=False)   # 1..4

    file_url: Mapped[Optional[str]] = mapped_column(String(512), nullable=True)
    file_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    summary: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    status: Mapped[str] = mapped_column(
        String(20), default=Form24QStatus.DRAFT, nullable=False, index=True,
    )
    challan_number: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True,
    )
    submitted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    accepted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )

    generated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    generated_by_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("user.id", ondelete="SET NULL"), nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc), nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc), nullable=False,
    )


# ----- Gratuity computation snapshot --------------------------------


class GratuityComputation(Base):
    """Snapshot of a gratuity calculation. We persist these so finance
    can audit the figure later, even if the employee's last_drawn
    changes via a correction or a back-dated revision.
    """
    __tablename__ = "gratuity_computation"  # type: ignore[assignment]

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    employee_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("employee.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    config_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("gratuity_config.id", ondelete="SET NULL"),
        nullable=True,
    )
    # Optional FK to the exit Resignation row, when this is the
    # exit-time figure.
    resignation_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("resignation.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )

    as_of: Mapped[pydate] = mapped_column(
        Date, nullable=False, index=True,
    )                                       # the "today" the figure
                                            # represents (last_working_day
                                            # for exits, today() for accrual)

    last_drawn_basic_da: Mapped[float] = mapped_column(
        Float, nullable=False,
    )
    raw_years: Mapped[float] = mapped_column(Float, nullable=False)
    rounded_years: Mapped[int] = mapped_column(Integer, nullable=False)
    is_eligible: Mapped[bool] = mapped_column(
        Boolean, nullable=False,
    )
    computed_amount: Mapped[float] = mapped_column(Float, nullable=False)
    capped_amount: Mapped[float] = mapped_column(Float, nullable=False)
    cap_applied: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False,
    )

    status: Mapped[str] = mapped_column(
        String(20), default=GratuityStatus.ACCRUED,
        nullable=False, index=True,
    )

    notes: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    computed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc), nullable=False,
    )
    computed_by_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("user.id", ondelete="SET NULL"), nullable=True,
    )
