export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    IMPERSONATE: (userId: number) => `/auth/impersonate/${userId}`,
    STOP_IMPERSONATION: '/auth/stop-impersonation',
    CHANGE_PASSWORD: '/auth/change-password',
  },
  HEALTH: '/health',
  ATTENDANCE: {
    MARK: '/attendance/mark',
    PUNCH_OUT: '/attendance/punch-out',
    TODAY: '/attendance/today',
    ALL: '/attendance/all',
    FLAGGED: '/attendance/flagged',
  },
  TIMESHEET: {
    TIMER_STATUS: '/timesheets/timer/status',
    TIMER_START: '/timesheets/timer/start',
    TIMER_PAUSE: '/timesheets/timer/pause',
    TIMER_RESUME: '/timesheets/timer/resume',
    TIMER_STOP: '/timesheets/timer/stop',
    MY: '/timesheets/my',
    MANUAL: '/timesheets/time-entries/manual',
    UTILIZATION_MY: '/timesheets/utilization/my',
    UTILIZATION_PROJECT: (projectId: number | string) =>
      `/timesheets/utilization/project/${projectId}`,
  },
  PROJECTS: {
    LIST: '/admin/projects',
    CREATE: '/projects/',
    DETAIL: (id: number | string) => `/projects/${id}`,
    MILESTONES: (id: number | string) => `/projects/${id}/milestones`,
    COST_BASELINE: (id: number | string) => `/projects/${id}/cost-baseline`,
    COST_CHANGE: (id: number | string) => `/projects/${id}/cost-change`,
    COST_APPROVAL_INBOX: '/projects/cost-approvals/inbox',
    COST_APPROVAL_ACTION: (id: number | string) => `/projects/cost-approvals/${id}/action`,
    MEMBERS: (id: number | string) => `/projects/${id}/members`,
    ADD_MEMBER: (id: number | string) => `/projects/${id}/members`,
    REMOVE_MEMBER: (projectId: number | string, userId: number | string) => `/projects/${projectId}/members/${userId}`,
    ALLOCATE_USERS: '/projects/users',
    COO_OVERVIEW: '/projects/coo/overview',
    DOCUMENTS: (id: number | string) => `/projects/${id}/documents`,
    DOCUMENT_UPLOAD: (id: number | string) => `/projects/${id}/documents/upload`,
    DOCUMENT_DOWNLOAD: (projectId: number | string, docId: number | string) => `/projects/${projectId}/documents/${docId}/download`,
    DOCUMENT_DELETE: (projectId: number | string, docId: number | string) => `/projects/${projectId}/documents/${docId}`,
    TEMPLATE: '/projects/template',
    BULK_UPLOAD: '/projects/bulk-upload',
    TEMPLATE_WITH_TASKS: '/projects/template-with-tasks',
    BULK_IMPORT_WITH_TASKS: '/projects/bulk-import-with-tasks',
  },
  TASKS: {
    CREATE: '/tasks/',
    MY_TASKS: '/tasks/my-tasks',
    MY_PENDING_ACTIONS_COUNT: '/tasks/my-pending-actions-count',
    BY_PROJECT: (projectId: number | string) => `/tasks/project/${projectId}`,
    DETAIL: (id: number) => `/tasks/${id}`,
    STATUS: (id: number) => `/tasks/${id}/status`,
    COMMENTS: (id: number) => `/tasks/${id}/comments`,
    SUBTASKS: (id: number) => `/tasks/${id}/subtasks`,
    SUBTASK: (id: number) => `/tasks/subtasks/${id}`,
    COMPLETION_REQUESTS: (taskId: number) => `/tasks/${taskId}/completion-requests`,
    COMPLETION_REVIEW: (taskId: number, requestId: number) => `/tasks/${taskId}/completion-requests/${requestId}/review`,
    COMPLETION_DOCUMENT: (taskId: number, requestId: number) => `/tasks/${taskId}/completion-requests/${requestId}/documents`,
    TIME_SUMMARY: (taskId: number) => `/tasks/${taskId}/time-summary`,
  },
  ADMIN: {
      REVIEW_DETAIL: (reviewId: number | string) => `/bd/bid-task-reviews/${reviewId}`,
    USERS: '/admin/users',
    USER_DETAIL: (id: number) => `/admin/users/${id}`,
    ROLES: '/admin/roles',
    ROLE_DETAIL: (id: number) => `/admin/roles/${id}`,
    PERMISSIONS: '/admin/permissions',
    LEAVE_TYPES: '/admin/leave-types',
    LEAVE_TYPE_DETAIL: (id: number) => `/admin/leave-types/${id}`,
    DEPARTMENTS: '/admin/departments',
    DEPARTMENT_DETAIL: (id: number) => `/admin/departments/${id}`,
    FUNCTIONAL_AREAS: '/admin/functional-areas',
    FUNCTIONAL_AREA_DETAIL: (id: number) => `/admin/functional-areas/${id}`,
    FUNCTIONAL_AREA_TEMPLATE: '/admin/functional-areas/template',
    FUNCTIONAL_AREA_BULK_UPLOAD: '/admin/functional-areas/bulk-upload',
    BID_LINE_ITEMS: '/admin/bid-line-items',
    BID_LINE_ITEM_DETAIL: (id: number | string) => `/admin/bid-line-items/${id}`,
    REQUIRED_DOCS: '/admin/required-documents',
    REQUIRED_DOC_DETAIL: (id: number | string) => `/admin/required-documents/${id}`,
    AUDIT_LOG: '/admin/audit-log',
    AUDIT_LOG_DISTINCT: '/admin/audit-log/distinct',
  },
  SHIFTS: {
    TEMPLATES: '/shifts/templates',
    TEMPLATE_DETAIL: (id: number) => `/shifts/templates/${id}`,
    ASSIGNMENTS: '/shifts/assignments',
    ASSIGNMENT_DETAIL: (id: number) => `/shifts/assignments/${id}`,
    ASSIGNMENTS_BULK: '/shifts/assignments/bulk',
    EFFECTIVE: '/shifts/effective',
    MY_CURRENT: '/shifts/my/current',
    MY_HISTORY: '/shifts/my/history',
  },
  GEO: {
    FENCES: '/geo/fences',
    FENCE_DETAIL: (id: number) => `/geo/fences/${id}`,
    EMPLOYEES: '/geo/employees',
    EMPLOYEE_DETAIL: (userId: number) => `/geo/employees/${userId}`,
    EMPLOYEE_TOGGLE: (userId: number) => `/geo/employees/${userId}/toggle`,
    EMPLOYEES_BULK: '/geo/employees/bulk',
    MY_EFFECTIVE: '/geo/my/effective',
  },
  LEAVE: {
    BALANCES: '/leave/balances',
    TYPES: '/leave/types',
    MY: '/leave/my',
    APPLY: '/leave/apply',
    ATTACHMENT_UPLOAD: '/leave/attachments',
    ATTACHMENT_DOWNLOAD: (filename: string) => `/leave/attachments/${filename}`,
    CANCEL: (id: number) => `/leave/${id}/cancel`,
    APPROVALS: '/leave/approvals/inbox',
    APPROVAL_ACTION: (id: number) => `/leave/approvals/${id}/action`,
    BALANCE_TEMPLATE: '/leave/balances/template',
    BALANCE_BULK_UPLOAD: '/leave/balances/bulk-upload',
    BALANCES_BY_USER: (userId: number) => `/leave/balances/user/${userId}`,
    BALANCES_ALL: '/leave/balances/all',
    HISTORY: '/leave/history',
    GRANT: '/leave/grant',
    COMP_OFF_GENERATE: '/leave/comp-off/generate',
    COMP_OFF_REQUESTS: '/leave/comp-off/requests',
    COMP_OFF_ACTION: (id: number) => `/leave/comp-off/requests/${id}/action`,
  },
  HR: {
    USERS: '/hr/users',
    ROLES: '/hr/roles',
    DEPARTMENTS: '/hr/departments',
    EMPLOYEES: '/hr/employees',
    MY_PROFILE: '/hr/employees/me',
    MY_PROFILE_UPDATE: '/hr/employees/me/profile',
    MY_KRA: '/hr/employees/me/kra',
    MY_AVATAR: '/hr/employees/me/avatar',
    EMPLOYEES_WITH_USER: '/hr/employees/with-user',
    EMPLOYEE_DETAIL: (id: number) => `/hr/employees/${id}`,
    EMPLOYEE_ROLES: (id: number) => `/hr/employees/${id}/roles`,
    DEACTIVATE: (id: number) => `/hr/employees/${id}/deactivate`,
    REACTIVATE: (id: number) => `/hr/employees/${id}/reactivate`,
    DELETE_EMPLOYEE: (id: number) => `/hr/employees/${id}`,
    EMPLOYEE_DELETE_BLOCKERS: (id: number) => `/hr/employees/${id}/delete-blockers`,
    EMPLOYEE_TRANSFER_WORK: (id: number) => `/hr/employees/${id}/transfer-work`,
    REASSIGN_PROJECT_MANAGER: (projectId: number) => `/hr/projects/${projectId}/manager`,
    REASSIGN_TASK_ASSIGNEE: (taskId: number) => `/hr/tasks/${taskId}/assignee`,
    REASSIGN_LEAD_OWNER: (leadId: number) => `/hr/leads/${leadId}/owner`,
    EMPLOYEE_DOCUMENTS: (id: number | string) => `/hr/employees/${id}/documents`,
    EMPLOYEE_DOCUMENT_UPLOAD: (id: number | string) => `/hr/employees/${id}/documents/upload`,
    EMPLOYEE_DOCUMENT_DELETE: (empId: number | string, docId: number | string) => `/hr/employees/${empId}/documents/${docId}`,
    EMPLOYEE_DOCUMENT_DOWNLOAD: (empId: number | string, docId: number | string) => `/hr/employees/${empId}/documents/${docId}/download`,
    EMPLOYEE_DOCUMENT_VERIFY: (empId: number | string, docId: number | string) => `/hr/employees/${empId}/documents/${docId}/verify`,
    EMPLOYEE_DOCUMENT_REJECT: (empId: number | string, docId: number | string) => `/hr/employees/${empId}/documents/${docId}/reject`,
    EMPLOYEE_REQUIRED_STATUS: (empId: number | string) => `/hr/employees/${empId}/documents/required-status`,
    MY_REQUIRED_STATUS: '/hr/employees/me/documents/required-status',
    MY_DOCUMENTS: '/hr/employees/me/documents',
    MY_DOCUMENT_UPLOAD: '/hr/employees/me/documents/upload',
    MY_DOCUMENT_DOWNLOAD: (docId: number | string) => `/hr/employees/me/documents/${docId}/download`,
    MY_DOCUMENT_DELETE: (docId: number | string) => `/hr/employees/me/documents/${docId}`,
    ORG_CHART: '/hr/org-chart',
    UPCOMING_CELEBRATIONS: '/hr/celebrations/upcoming',
    EMPLOYEE_ASSETS: (empId: number | string) => `/hr/employees/${empId}/assets`,
    MY_ASSETS: '/hr/employees/me/assets',
    ASSET_UPDATE: (assetId: number | string) => `/hr/assets/${assetId}`,
    ASSET_DELETE: (assetId: number | string) => `/hr/assets/${assetId}`,
    EMPLOYEE_CONFIRM: (id: number) => `/hr/employees/${id}/confirm`,
    TEMPLATE: '/hr/employees/template',
    BULK_UPLOAD: '/hr/employees/bulk-upload',
    ATTENDANCE_CORRECTIONS: '/hr/attendance-corrections',
    ATTENDANCE_CORRECTION_ACTION: (id: number) => `/hr/attendance-corrections/${id}/action`,
    HOLIDAYS: '/hr/holidays',
    HOLIDAY_DETAIL: (id: number) => `/hr/holidays/${id}`,
    POLICIES: '/hr/policies',
    POLICY_UPLOAD: '/hr/policies/upload',
    POLICY_DELETE: (id: number) => `/hr/policies/${id}`,
    POLICY_DOWNLOAD: (id: number) => `/hr/policies/${id}/download`,
    POLICY_ACKNOWLEDGE: (id: number) => `/hr/policies/${id}/acknowledge`,
    POLICY_ACKNOWLEDGEMENTS: (id: number) => `/hr/policies/${id}/acknowledgements`,
    DASHBOARD_STATS: '/hr/dashboard/stats',
    LETTERS: '/hr/letters',
    LETTER_TYPES: '/hr/letters/types',
    LETTER_GENERATE: '/hr/letters/generate',
    LETTER_DOWNLOAD: (id: number) => `/hr/letters/${id}/download`,
    SALARY_CALCULATE: (empId: number) => `/hr/employees/${empId}/salary-calculate`,
    SALARY_PREVIEW: '/hr/salary/preview',
    ADVANCES: '/hr/salary/advances',
    ADVANCE_MY: '/hr/salary/advances/my',
    ADVANCE_DETAIL: (id: number) => `/hr/salary/advances/${id}`,
    ADVANCE_WRITE_OFF: (id: number) => `/hr/salary/advances/${id}/write-off`,
    ADVANCE_CANCEL: (id: number) => `/hr/salary/advances/${id}/cancel`,
    ADVANCE_RECOVER: (id: number) => `/hr/salary/advances/${id}/recover`,
    ADVANCE_RECOVERIES: (id: number) => `/hr/salary/advances/${id}/recoveries`,
    PARTIAL_PAYMENT: (runId: number, lineId: number) => `/hr/salary/payroll/${runId}/lines/${lineId}/partial-payment`,
    RELEASE_HELD: (runId: number) => `/hr/salary/payroll/${runId}/release-held`,
    HELD_SALARIES: '/hr/salary/payroll/held-salaries',
    DISBURSE: (lineId: number) => `/hr/salary/payroll/lines/${lineId}/disburse`,
    DISBURSEMENTS: (lineId: number) => `/hr/salary/payroll/lines/${lineId}/disbursements`,
    PAYROLL: {
      DASHBOARD: '/hr/payroll/dashboard',
      CREATE_RUN: '/hr/payroll/run',
      ATTENDANCE_CHECK: (id: number) => `/hr/payroll/${id}/attendance-check`,
      LOCK_ATTENDANCE: (id: number) => `/hr/payroll/${id}/lock-attendance`,
      LOCK_LEAVES: (id: number) => `/hr/payroll/${id}/lock-leaves`,
      GENERATE_DRAFT: (id: number) => `/hr/payroll/${id}/generate-draft`,
      FINALIZE: (id: number) => `/hr/payroll/${id}/finalize`,
      PUBLISH: (id: number) => `/hr/payroll/${id}/publish`,
      LINES: (id: number) => `/hr/payroll/${id}/lines`,
      LINE_UPDATE: (runId: number, lineId: number) => `/hr/payroll/${runId}/lines/${lineId}`,
      MY_PAYSLIPS: '/hr/payroll/my-payslips',
    },
  },
  APPROVALS: {
    INBOX: '/approvals/inbox',
    DETAIL: (id: number) => `/approvals/${id}`,
    RESOURCE: (id: number) => `/approvals/${id}/resource`,
    ACTION: (id: number) => `/approvals/${id}/action`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications/',
    MARK_READ: (id: number) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/mark-all-read',
  },
  REPORTS: {
    SUMMARY: '/reports/summary',
    ATTENDANCE: '/reports/attendance',
    UTILIZATION: '/reports/utilization',
    LEAVE: '/reports/leave',
    PROJECT_COSTS: '/reports/project-costs',
  },
  BD: {
    LEADS: '/bd/leads',
    PIPELINE: '/bd/pipeline',
    DASHBOARD: '/bd/dashboard',
    PROJECT_MANAGERS: '/bd/users/project-managers',
    COO_USERS: '/bd/users/coo-users',
    ELIGIBLE_PORTFOLIO_MANAGERS: (leadId: number | string) =>
      `/bd/leads/${leadId}/eligible-portfolio-managers`,
    ESTIMATE_APPROVERS: '/bd/users/estimate-approvers',
    REPORTS: {
      ESTIMATE_ACCURACY: '/bd/reports/estimate-accuracy',
    },
    LEAD_DETAIL: (id: number | string) => `/bd/leads/${id}`,
    LEAD_ACTIVITIES: (id: number | string) => `/bd/leads/${id}/activities`,
    LEAD_ESTIMATES: (id: number | string) => `/bd/leads/${id}/estimates`,
    LEAD_DOCUMENTS: (id: number | string) => `/bd/leads/${id}/documents`,
    LEAD_DOCUMENT_DOWNLOAD: (
      leadId: number | string,
      docId: number | string,
    ) => `/bd/leads/${leadId}/documents/${docId}/download`,
    LEAD_DOCUMENT_DELETE: (
      leadId: number | string,
      docId: number | string,
    ) => `/bd/leads/${leadId}/documents/${docId}`,
    LEAD_ESTIMATE_APPROVALS: (id: number | string) => `/bd/leads/${id}/estimate-approvals`,
    CONVERT_TO_PROJECT: (id: number) => `/bd/leads/${id}/convert-to-project`,
    ESTIMATE_DETAIL: (id: number | string) => `/bd/estimates/${id}`,
    ESTIMATE_SUBMIT: (id: number | string) => `/bd/estimates/${id}/submit`,
    ESTIMATE_ARCHIVE: (id: number | string) => `/bd/estimates/${id}/archive`,
    ESTIMATE_COMPARE: (id: number | string, otherId: number | string) => `/bd/estimates/${id}/compare?other_id=${otherId}`,
    ESTIMATE_GENERATE_PROPOSAL: (id: number | string) => `/bd/estimates/${id}/generate-proposal`,
    ESTIMATE_QUOTATIONS: (id: number | string) => `/bd/estimates/${id}/quotations`,
    QUOTATION_DETAIL: (id: number | string) => `/bd/quotations/${id}`,
    QUOTATION_PDF: (id: number | string) => `/bd/quotations/${id}/pdf`,

    BID_TASKS: {
      CREATE: (leadId: number | string) => `/bd/leads/${leadId}/bid-tasks`,
      LIST: (leadId: number | string) => `/bd/leads/${leadId}/bid-tasks`,
      ASSIGN: (leadId: number | string, bidTaskId: number | string) =>
        `/bd/leads/${leadId}/bid-tasks/${bidTaskId}/assign`,
      EVALUATIONS: (leadId: number | string) => `/bd/leads/${leadId}/bid-evaluations`,
      PM_SUBMISSIONS_SUMMARY: (leadId: number | string, estimateVersionId: number | string) =>
        `/bd/leads/${leadId}/estimates/${estimateVersionId}/pm-submissions-summary`,
      APPLY_PM_SUBMISSIONS: (leadId: number | string, estimateVersionId: number | string) =>
        `/bd/leads/${leadId}/estimates/${estimateVersionId}/apply-pm-submissions`,
      MY_REQUESTS: '/bd/bid-requests/my',
      ASSIGNMENT_LATEST_REVIEW: (assignmentId: number | string) =>
        `/bd/bid-task-assignments/${assignmentId}/reviews/latest`,
      REVIEW_UPDATE: (reviewId: number | string) => `/bd/bid-task-reviews/${reviewId}`,
      REVIEW_SUBMIT: (reviewId: number | string) => `/bd/bid-task-reviews/${reviewId}/submit`,
      REVIEW_REQUEST_REVISION: (reviewId: number | string) =>
        `/bd/bid-task-reviews/${reviewId}/request-revision`,
      REVIEW_ACCEPT: (reviewId: number | string) =>
        `/bd/bid-task-reviews/${reviewId}/accept`,
      ASSIGN_UNASSIGNED_TO_COO: (leadId: number | string) =>
        `/bd/leads/${leadId}/bid-tasks/assign-unassigned-to-coo`,
      ARCHIVE: (leadId: number | string, bidTaskId: number | string) =>
        `/bd/leads/${leadId}/bid-tasks/${bidTaskId}/archive`,
      DELETE: (leadId: number | string, bidTaskId: number | string) =>
        `/bd/leads/${leadId}/bid-tasks/${bidTaskId}`,
    },
    BID_LINE_ITEMS: '/bd/bid-line-items',
  },
  CLIENTS: {
    LIST: '/clients/',
    PAGE: '/clients/page',
    CREATE: '/clients/',
    DETAIL: (id: number | string) => `/clients/${id}`,
    DELETE: (id: number | string) => `/clients/${id}`,
    DELETE_BLOCKERS: (id: number | string) => `/clients/${id}/delete-blockers`,
    DETAILS: (id: number | string) => `/clients/${id}/details`,
    TEMPLATE: '/clients/template',
    BULK_UPLOAD: '/clients/bulk-upload',
    EXPORT: '/clients/export',
  },
  EXIT: {
    RESIGN: '/exit/resign',
    WITHDRAW: '/exit/resign/withdraw',
    MY_RESIGNATION: '/exit/resign/my',
    EXIT_INTERVIEW: '/exit/resign/exit-interview',
    RESIGNATIONS: '/exit/resignations',
    RESIGNATION_DETAIL: (id: number) => `/exit/resignations/${id}`,
    ACCEPT: (id: number) => `/exit/resignations/${id}/accept`,
    REJECT: (id: number) => `/exit/resignations/${id}/reject`,
    CANCEL: (id: number) => `/exit/resignations/${id}/cancel`,
    EXPEDITE: (id: number) => `/exit/resignations/${id}/expedite`,
    REQUEST_EXIT_INTERVIEW: (id: number) => `/exit/resignations/${id}/request-exit-interview`,
    EXIT_INTERVIEW_REMARKS: (id: number) => `/exit/resignations/${id}/exit-interview/remarks`,
    INITIATE_CLEARANCE: (id: number) => `/exit/resignations/${id}/clearance`,
    CLEARANCE_ACTION: (id: number) => `/exit/clearance/${id}/action`,
    MY_CLEARANCE: '/exit/clearance/my',
    RELEASE: (id: number) => `/exit/resignations/${id}/release`,
  },
  RECRUITMENT: {
    REQUISITIONS: '/recruitment/',
    SUBMIT: (id: number) => `/recruitment/${id}/submit`,
    DETAIL: (id: number) => `/recruitment/${id}`,
    APPLICANTS: '/recruitment/applicants',
    APPLICANT_DETAIL: (id: number) => `/recruitment/applicants/${id}`,
    APPLICANT_STATUS: (id: number) => `/recruitment/applicants/${id}/status`,
    INTERVIEWS: '/recruitment/interviews',
  },
};
