from __future__ import annotations

from io import BytesIO
from typing import Any, Dict

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


NOT_SPECIFIED = "(Not specified)"


def _normalize(value: Any) -> str:
    return "" if value is None else str(value)


def _render_multiline(
    c: canvas.Canvas,
    x: float,
    y: float,
    width_chars: int,
    text: str,
    max_lines: int,
    line_step: float,
    ensure_space,
) -> float:
    for line in (text or "").splitlines()[:max_lines]:
        ensure_space()
        c.drawString(x, y, line[:width_chars])
        y -= line_step
    return y


def _render_scope_section(
    c: canvas.Canvas,
    margin_x: float,
    y: float,
    scope: Dict[str, Any],
    ensure_space,
) -> float:
    ensure_space()
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_x, y, "Scope")
    y -= 8 * mm

    included = (scope.get("included") or "").strip() or NOT_SPECIFIED
    excluded = (scope.get("excluded") or "").strip() or NOT_SPECIFIED
    assumptions = (scope.get("assumptions") or "").strip() or NOT_SPECIFIED

    for heading, body in (
        ("Included", included),
        ("Excluded", excluded),
        ("Assumptions", assumptions),
    ):
        ensure_space()
        c.setFont("Helvetica-Bold", 10)
        c.drawString(margin_x, y, heading)
        y -= 6 * mm
        c.setFont("Helvetica", 10)
        y = _render_multiline(
            c,
            margin_x,
            y,
            120,
            body,
            30,
            5.5 * mm,
            ensure_space,
        )
        y -= 3 * mm

    return y


def _render_phases_section(
    c: canvas.Canvas,
    margin_x: float,
    y: float,
    phases: list,
    ensure_space,
) -> float:
    ensure_space()
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_x, y, "Phases")
    y -= 8 * mm
    c.setFont("Helvetica", 10)

    if not phases:
        c.drawString(margin_x, y, "(No phases defined)")
        return y - 6 * mm

    for p in phases[:50]:
        ensure_space()
        name = _normalize(p.get("name", ""))
        duration = _normalize(p.get("duration", ""))
        desc = _normalize(p.get("description", "") or "")
        c.setFont("Helvetica-Bold", 10)
        c.drawString(margin_x, y, f"- {name} ({duration} days)")
        y -= 6 * mm
        if desc.strip():
            ensure_space()
            c.setFont("Helvetica", 10)
            c.drawString(margin_x + 6 * mm, y, desc[:140])
            y -= 6 * mm

    return y


def render_quotation_pdf(snapshot_data: Dict[str, Any]) -> bytes:
    """Render a minimal, production-safe quotation PDF from a snapshot."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    _, height = A4

    margin_x = 18 * mm
    y = height - 18 * mm
    line_h = 6.5 * mm

    def ensure_space() -> None:
        nonlocal y
        if y < 20 * mm:
            c.showPage()
            y = height - 18 * mm

    def text_row(label: str, value: str) -> None:
        nonlocal y
        ensure_space()
        c.setFont("Helvetica-Bold", 10)
        c.drawString(margin_x, y, label)
        c.setFont("Helvetica", 10)
        c.drawString(margin_x + 55 * mm, y, value)
        y -= line_h

    data = snapshot_data or {}
    proposal = data.get("proposal_info") or {}
    lead = data.get("lead_info") or {}
    fin = data.get("financial_summary") or {}
    scope = data.get("scope") or {}
    phases = data.get("phases") or []

    c.setFont("Helvetica-Bold", 18)
    c.drawString(margin_x, y, "QUOTATION")
    y -= 12 * mm

    version_name = proposal.get("version_name", "")
    version_number = proposal.get("version_number", "")
    text_row("Version", f"{version_name} (V{version_number})")
    text_row("Generated At", _normalize(proposal.get("generated_at", "")))
    text_row("Generated By", _normalize(proposal.get("generated_by", "")))
    y -= 3 * mm

    text_row("Lead", _normalize(lead.get("title", "")))
    text_row("Client", _normalize(lead.get("account", "")))
    text_row("Contact", _normalize(lead.get("contact", "")))
    y -= 3 * mm

    currency = _normalize(fin.get("currency", ""))
    total_price = fin.get("total_price")
    text_row("Total Price", f"{currency} {total_price}")
    text_row("Margin %", _normalize(fin.get("margin_percent", "")))
    text_row("Contingency %", _normalize(fin.get("contingency_percent", "")))

    y -= 6 * mm
    y = _render_scope_section(c, margin_x, y, scope, ensure_space)
    y = _render_phases_section(c, margin_x, y, phases, ensure_space)

    c.showPage()
    c.save()
    return buf.getvalue()
