"""use_timezone_aware_datetimes

Revision ID: 01e0a6b513ac
Revises: e59d468ff78b
Create Date: 2026-02-11 05:17:54.050775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e0a6b513ac'
down_revision: Union[str, None] = 'e59d468ff78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
