"""add system settings table

Revision ID: 0ae23cdc4f23
Revises: ad3ab7b15780
Create Date: 2026-02-14 11:37:46.723403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae23cdc4f23'
down_revision: Union[str, None] = 'ad3ab7b15780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systemsetting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_systemsetting_key'), 'systemsetting', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_systemsetting_key'), table_name='systemsetting')
    op.drop_table('systemsetting')
    # ### end Alembic commands ###
