"""consolidated payroll and notifications

Revision ID: 0b9ea22ca449
Revises: 2a8e00e4b24c
Create Date: 2026-02-13 21:22:11.953124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9ea22ca449'
down_revision: Union[str, None] = '2a8e00e4b24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('payrollrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ATTENDANCE_LOCKED', 'LEAVES_LOCKED', 'DRAFT_GENERATED', 'FINALIZED', 'PUBLISHED', name='payrollrunstatus'), nullable=False),
    sa.Column('total_gross', sa.Float(), nullable=False),
    sa.Column('total_net', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=False),
    sa.Column('attendance_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leaves_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finalized_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payrollrun_id'), 'payrollrun', ['id'], unique=False)
    op.create_index(op.f('ix_payrollrun_status'), 'payrollrun', ['status'], unique=False)
    op.create_table('payrollline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('payable_days', sa.Float(), nullable=False),
    sa.Column('lop_days', sa.Float(), nullable=False),
    sa.Column('gross_pay', sa.Float(), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('allowances', sa.JSON(), nullable=True),
    sa.Column('deductions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payrollrun.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payrollline_id'), 'payrollline', ['id'], unique=False)
    op.create_index(op.f('ix_payrollline_payroll_run_id'), 'payrollline', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_payrollline_user_id'), 'payrollline', ['user_id'], unique=False)
    op.create_table('payslip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_line_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payroll_line_id'], ['payrollline.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_id'), 'payslip', ['id'], unique=False)
    op.create_index(op.f('ix_payslip_payroll_line_id'), 'payslip', ['payroll_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payslip_payroll_line_id'), table_name='payslip')
    op.drop_index(op.f('ix_payslip_id'), table_name='payslip')
    op.drop_table('payslip')
    op.drop_index(op.f('ix_payrollline_user_id'), table_name='payrollline')
    op.drop_index(op.f('ix_payrollline_payroll_run_id'), table_name='payrollline')
    op.drop_index(op.f('ix_payrollline_id'), table_name='payrollline')
    op.drop_table('payrollline')
    op.drop_index(op.f('ix_payrollrun_status'), table_name='payrollrun')
    op.drop_index(op.f('ix_payrollrun_id'), table_name='payrollrun')
    op.drop_table('payrollrun')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
