"""Add lead_id to project

Revision ID: 163a6257061f
Revises: 1860f33c7883
Create Date: 2026-02-16 21:26:14.197245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163a6257061f'
down_revision: Union[str, None] = '1860f33c7883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'lead', ['lead_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'lead_id')
    # ### end Alembic commands ###
