"""add_lead_bid_task_workflow

Revision ID: 17441bc84e66
Revises: f8b706fff48b
Create Date: 2026-03-11 07:04:58.466071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


FK_USER = "user.id"
FK_LEAD = "lead.id"
FK_ESTIMATE_VERSION = "estimateversion.id"
ONDELETE_CASCADE = "CASCADE"
ONDELETE_SET_NULL = "SET NULL"


# revision identifiers, used by Alembic.
revision: str = '17441bc84e66'
down_revision: Union[str, None] = 'f8b706fff48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lead_bid_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            [FK_USER],
            ondelete=ONDELETE_SET_NULL,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            [FK_LEAD],
            ondelete=ONDELETE_CASCADE,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_bid_task_created_by_id"),
        "lead_bid_task",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_bid_task_id"),
        "lead_bid_task",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_bid_task_lead_id"),
        "lead_bid_task",
        ["lead_id"],
        unique=False,
    )

    op.create_table(
        "lead_bid_task_assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bid_task_id", sa.Integer(), nullable=False),
        sa.Column("pm_user_id", sa.Integer(), nullable=False),
        sa.Column("assigned_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            [FK_USER],
            ondelete=ONDELETE_SET_NULL,
        ),
        sa.ForeignKeyConstraint(
            ["bid_task_id"],
            ["lead_bid_task.id"],
            ondelete=ONDELETE_CASCADE,
        ),
        sa.ForeignKeyConstraint(
            ["pm_user_id"],
            [FK_USER],
            ondelete=ONDELETE_CASCADE,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bid_task_id",
            "pm_user_id",
            name="uq_lead_bid_task_assignment_task_pm",
        ),
    )
    op.create_index(
        op.f("ix_lead_bid_task_assignment_assigned_by_id"),
        "lead_bid_task_assignment",
        ["assigned_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_bid_task_assignment_bid_task_id"),
        "lead_bid_task_assignment",
        ["bid_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_bid_task_assignment_id"),
        "lead_bid_task_assignment",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_bid_task_assignment_pm_user_id"),
        "lead_bid_task_assignment",
        ["pm_user_id"],
        unique=False,
    )

    op.create_table(
        "lead_bid_task_review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("estimate_version_id", sa.Integer(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "accepted",
                "revision_requested",
                name="leadbidtaskreviewstatus",
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column(
            "total_hours",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column(
            "total_cost",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column("pm_notes", sa.Text(), nullable=True),
        sa.Column("bd_notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("previous_review_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["lead_bid_task_assignment.id"],
            ondelete=ONDELETE_CASCADE,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            [FK_USER],
            ondelete=ONDELETE_SET_NULL,
        ),
        sa.ForeignKeyConstraint(
            ["estimate_version_id"],
            [FK_ESTIMATE_VERSION],
            ondelete=ONDELETE_CASCADE,
        ),
        sa.ForeignKeyConstraint(
            ["previous_review_id"],
            ["lead_bid_task_review.id"],
            ondelete=ONDELETE_SET_NULL,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "assignment_id",
            "estimate_version_id",
            "revision_number",
            name=(
                "uq_lead_bid_task_review_assignment_"
                "version_revision"
            ),
        ),
    )
    op.create_index(
        op.f("ix_lead_bid_task_review_assignment_id"),
        "lead_bid_task_review",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_bid_task_review_created_by_id"),
        "lead_bid_task_review",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_bid_task_review_estimate_version_id"),
        "lead_bid_task_review",
        ["estimate_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_bid_task_review_id"),
        "lead_bid_task_review",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_bid_task_review_previous_review_id"),
        "lead_bid_task_review",
        ["previous_review_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_bid_task_review_status"),
        "lead_bid_task_review",
        ["status"],
        unique=False,
    )

    op.create_table(
        "lead_bid_task_review_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "hours",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column(
            "cost",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["lead_bid_task_review.id"],
            ondelete=ONDELETE_CASCADE,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_bid_task_review_line_id"),
        "lead_bid_task_review_line",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_bid_task_review_line_review_id"),
        "lead_bid_task_review_line",
        ["review_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_lead_bid_task_review_line_review_id"),
        table_name="lead_bid_task_review_line",
    )
    op.drop_index(
        op.f("ix_lead_bid_task_review_line_id"),
        table_name="lead_bid_task_review_line",
    )
    op.drop_table("lead_bid_task_review_line")

    op.drop_index(
        op.f("ix_lead_bid_task_review_status"),
        table_name="lead_bid_task_review",
    )
    op.drop_index(
        op.f("ix_lead_bid_task_review_previous_review_id"),
        table_name="lead_bid_task_review",
    )
    op.drop_index(
        op.f("ix_lead_bid_task_review_id"),
        table_name="lead_bid_task_review",
    )
    op.drop_index(
        op.f("ix_lead_bid_task_review_estimate_version_id"),
        table_name="lead_bid_task_review",
    )
    op.drop_index(
        op.f("ix_lead_bid_task_review_created_by_id"),
        table_name="lead_bid_task_review",
    )
    op.drop_index(
        op.f("ix_lead_bid_task_review_assignment_id"),
        table_name="lead_bid_task_review",
    )
    op.drop_table("lead_bid_task_review")

    op.drop_index(
        op.f("ix_lead_bid_task_assignment_pm_user_id"),
        table_name="lead_bid_task_assignment",
    )
    op.drop_index(
        op.f("ix_lead_bid_task_assignment_id"),
        table_name="lead_bid_task_assignment",
    )
    op.drop_index(
        op.f("ix_lead_bid_task_assignment_bid_task_id"),
        table_name="lead_bid_task_assignment",
    )
    op.drop_index(
        op.f("ix_lead_bid_task_assignment_assigned_by_id"),
        table_name="lead_bid_task_assignment",
    )
    op.drop_table("lead_bid_task_assignment")

    op.drop_index(
        op.f("ix_lead_bid_task_lead_id"),
        table_name="lead_bid_task",
    )
    op.drop_index(op.f("ix_lead_bid_task_id"), table_name="lead_bid_task")
    op.drop_index(
        op.f("ix_lead_bid_task_created_by_id"),
        table_name="lead_bid_task",
    )
    op.drop_table("lead_bid_task")
    # ### end Alembic commands ###
