"""Add onboarding tables

Revision ID: 1860f33c7883
Revises: 907aecdffdec
Create Date: 2026-02-16 11:19:11.613986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1860f33c7883'
down_revision: Union[str, None] = '907aecdffdec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboardingprocess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='onboardingstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_id')
    )
    op.create_index(op.f('ix_onboardingprocess_id'), 'onboardingprocess', ['id'], unique=False)
    op.create_table('onboardingtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='onboardingstatus'), nullable=False),
    sa.Column('actor_role', sa.String(length=100), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['onboardingprocess.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboardingtask_id'), 'onboardingtask', ['id'], unique=False)
    op.create_index(op.f('ix_onboardingtask_process_id'), 'onboardingtask', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboardingtask_process_id'), table_name='onboardingtask')
    op.drop_index(op.f('ix_onboardingtask_id'), table_name='onboardingtask')
    op.drop_table('onboardingtask')
    op.drop_index(op.f('ix_onboardingprocess_id'), table_name='onboardingprocess')
    op.drop_table('onboardingprocess')
    # ### end Alembic commands ###
