"""add_hr_features

Revision ID: 25e2e921d8af
Revises: b7239791cac0
Create Date: 2026-02-13 11:46:47.070712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e2e921d8af'
down_revision: Union[str, None] = 'b7239791cac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidaycalendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidaycalendar_date'), 'holidaycalendar', ['date'], unique=False)
    op.create_index(op.f('ix_holidaycalendar_id'), 'holidaycalendar', ['id'], unique=False)
    op.create_index(op.f('ix_holidaycalendar_location'), 'holidaycalendar', ['location'], unique=False)
    op.create_index(op.f('ix_holidaycalendar_name'), 'holidaycalendar', ['name'], unique=False)
    op.create_table('policydocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policydocument_id'), 'policydocument', ['id'], unique=False)
    op.create_index(op.f('ix_policydocument_title'), 'policydocument', ['title'], unique=False)
    op.create_table('policyacknowledgement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policydocument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policyacknowledgement_id'), 'policyacknowledgement', ['id'], unique=False)
    op.create_index(op.f('ix_policyacknowledgement_policy_id'), 'policyacknowledgement', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policyacknowledgement_user_id'), 'policyacknowledgement', ['user_id'], unique=False)
    op.create_table('attendancecorrectionrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('requested_mode', sa.String(length=50), nullable=False),
    sa.Column('requested_remarks', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendancecorrectionrequest_created_by_id'), 'attendancecorrectionrequest', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_attendancecorrectionrequest_id'), 'attendancecorrectionrequest', ['id'], unique=False)
    op.create_index(op.f('ix_attendancecorrectionrequest_status'), 'attendancecorrectionrequest', ['status'], unique=False)
    op.create_index(op.f('ix_attendancecorrectionrequest_user_id'), 'attendancecorrectionrequest', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendancecorrectionrequest_user_id'), table_name='attendancecorrectionrequest')
    op.drop_index(op.f('ix_attendancecorrectionrequest_status'), table_name='attendancecorrectionrequest')
    op.drop_index(op.f('ix_attendancecorrectionrequest_id'), table_name='attendancecorrectionrequest')
    op.drop_index(op.f('ix_attendancecorrectionrequest_created_by_id'), table_name='attendancecorrectionrequest')
    op.drop_table('attendancecorrectionrequest')
    op.drop_index(op.f('ix_policyacknowledgement_user_id'), table_name='policyacknowledgement')
    op.drop_index(op.f('ix_policyacknowledgement_policy_id'), table_name='policyacknowledgement')
    op.drop_index(op.f('ix_policyacknowledgement_id'), table_name='policyacknowledgement')
    op.drop_table('policyacknowledgement')
    op.drop_index(op.f('ix_policydocument_title'), table_name='policydocument')
    op.drop_index(op.f('ix_policydocument_id'), table_name='policydocument')
    op.drop_table('policydocument')
    op.drop_index(op.f('ix_holidaycalendar_name'), table_name='holidaycalendar')
    op.drop_index(op.f('ix_holidaycalendar_location'), table_name='holidaycalendar')
    op.drop_index(op.f('ix_holidaycalendar_id'), table_name='holidaycalendar')
    op.drop_index(op.f('ix_holidaycalendar_date'), table_name='holidaycalendar')
    op.drop_table('holidaycalendar')
    # ### end Alembic commands ###
