"""add current_version_id to lead

Revision ID: 2744776c1c81
Revises: 3339b33718a8
Create Date: 2026-02-14 11:15:43.729321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2744776c1c81'
down_revision: Union[str, None] = '3339b33718a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('current_version_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'current_version_id')
    # ### end Alembic commands ###
