"""add_task_and_project_tables

Revision ID: 276236fd2e6e
Revises: efae53888a25
Create Date: 2026-02-11 07:08:07.008783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276236fd2e6e'
down_revision: Union[str, None] = 'efae53888a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_code'), 'project', ['code'], unique=True)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_table('project_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_member_id'), 'project_member', ['id'], unique=False)
    op.create_index(op.f('ix_project_member_project_id'), 'project_member', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_member_user_id'), 'project_member', ['user_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assignee_id'), 'task', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_task_creator_id'), 'task', ['creator_id'], unique=False)
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_index(op.f('ix_task_project_id'), 'task', ['project_id'], unique=False)
    op.create_table('subtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtask_id'), 'subtask', ['id'], unique=False)
    op.create_index(op.f('ix_subtask_task_id'), 'subtask', ['task_id'], unique=False)
    op.create_table('taskattachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskattachment_id'), 'taskattachment', ['id'], unique=False)
    op.create_index(op.f('ix_taskattachment_task_id'), 'taskattachment', ['task_id'], unique=False)
    op.create_index(op.f('ix_taskattachment_uploader_id'), 'taskattachment', ['uploader_id'], unique=False)
    op.create_table('taskcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskcomment_id'), 'taskcomment', ['id'], unique=False)
    op.create_index(op.f('ix_taskcomment_task_id'), 'taskcomment', ['task_id'], unique=False)
    op.create_index(op.f('ix_taskcomment_user_id'), 'taskcomment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskcomment_user_id'), table_name='taskcomment')
    op.drop_index(op.f('ix_taskcomment_task_id'), table_name='taskcomment')
    op.drop_index(op.f('ix_taskcomment_id'), table_name='taskcomment')
    op.drop_table('taskcomment')
    op.drop_index(op.f('ix_taskattachment_uploader_id'), table_name='taskattachment')
    op.drop_index(op.f('ix_taskattachment_task_id'), table_name='taskattachment')
    op.drop_index(op.f('ix_taskattachment_id'), table_name='taskattachment')
    op.drop_table('taskattachment')
    op.drop_index(op.f('ix_subtask_task_id'), table_name='subtask')
    op.drop_index(op.f('ix_subtask_id'), table_name='subtask')
    op.drop_table('subtask')
    op.drop_index(op.f('ix_task_project_id'), table_name='task')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_index(op.f('ix_task_creator_id'), table_name='task')
    op.drop_index(op.f('ix_task_assignee_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_project_member_user_id'), table_name='project_member')
    op.drop_index(op.f('ix_project_member_project_id'), table_name='project_member')
    op.drop_index(op.f('ix_project_member_id'), table_name='project_member')
    op.drop_table('project_member')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_index(op.f('ix_project_code'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
