"""add approvals inbox and notifications

Revision ID: 2a8e00e4b24c
Revises: 16f3af8bc154
Create Date: 2026-02-13 20:59:10.267880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8e00e4b24c'
down_revision: Union[str, None] = '16f3af8bc154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvalitem', sa.Column('requested_by_id', sa.Integer(), nullable=True))
    op.add_column('approvalitem', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('approvalitem', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'approvalitem', 'user', ['requested_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'approvalitem', type_='foreignkey')
    op.drop_column('approvalitem', 'due_date')
    op.drop_column('approvalitem', 'created_at')
    op.drop_column('approvalitem', 'requested_by_id')
    # ### end Alembic commands ###
