"""add proposal snapshot model

Revision ID: 2c4204d5b2af
Revises: 0ae23cdc4f23
Create Date: 2026-02-14 11:43:59.624460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4204d5b2af'
down_revision: Union[str, None] = '0ae23cdc4f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposalsnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['estimateversion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposalsnapshot_id'), 'proposalsnapshot', ['id'], unique=False)
    op.create_index(op.f('ix_proposalsnapshot_version_id'), 'proposalsnapshot', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposalsnapshot_version_id'), table_name='proposalsnapshot')
    op.drop_index(op.f('ix_proposalsnapshot_id'), table_name='proposalsnapshot')
    op.drop_table('proposalsnapshot')
    # ### end Alembic commands ###
