"""add project delivery models

Revision ID: 2dbeb3933061
Revises: 25e2e921d8af
Create Date: 2026-02-13 19:56:55.987936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbeb3933061'
down_revision: Union[str, None] = '25e2e921d8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costbaseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costbaseline_id'), 'costbaseline', ['id'], unique=False)
    op.create_index(op.f('ix_costbaseline_project_id'), 'costbaseline', ['project_id'], unique=False)
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestone_id'), 'milestone', ['id'], unique=False)
    op.create_index(op.f('ix_milestone_project_id'), 'milestone', ['project_id'], unique=False)
    op.create_table('costchangerequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=True),
    sa.Column('baseline_amount', sa.Float(), nullable=False),
    sa.Column('proposed_amount', sa.Float(), nullable=False),
    sa.Column('percent_change', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'NEEDS_CLARIFICATION', name='costchangestatus'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['costbaseline.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costchangerequest_id'), 'costchangerequest', ['id'], unique=False)
    op.create_index(op.f('ix_costchangerequest_project_id'), 'costchangerequest', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_costchangerequest_project_id'), table_name='costchangerequest')
    op.drop_index(op.f('ix_costchangerequest_id'), table_name='costchangerequest')
    op.drop_table('costchangerequest')
    op.drop_index(op.f('ix_milestone_project_id'), table_name='milestone')
    op.drop_index(op.f('ix_milestone_id'), table_name='milestone')
    op.drop_table('milestone')
    op.drop_index(op.f('ix_costbaseline_project_id'), table_name='costbaseline')
    op.drop_index(op.f('ix_costbaseline_id'), table_name='costbaseline')
    op.drop_table('costbaseline')
    # ### end Alembic commands ###
