"""add recruitment models

Revision ID: 31c5f3d43e97
Revises: 3762f48584f9
Create Date: 2026-02-16 14:58:06.960744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c5f3d43e97'
down_revision: Union[str, None] = '3762f48584f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manpowerrequisition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('positions_count', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='requisitionpriority'), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='employmenttype'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.String(length=100), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELED', name='requisitionstatus'), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manpowerrequisition_department'), 'manpowerrequisition', ['department'], unique=False)
    op.create_index(op.f('ix_manpowerrequisition_id'), 'manpowerrequisition', ['id'], unique=False)
    op.create_index(op.f('ix_manpowerrequisition_req_id'), 'manpowerrequisition', ['req_id'], unique=True)
    op.create_index(op.f('ix_manpowerrequisition_title'), 'manpowerrequisition', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manpowerrequisition_title'), table_name='manpowerrequisition')
    op.drop_index(op.f('ix_manpowerrequisition_req_id'), table_name='manpowerrequisition')
    op.drop_index(op.f('ix_manpowerrequisition_id'), table_name='manpowerrequisition')
    op.drop_index(op.f('ix_manpowerrequisition_department'), table_name='manpowerrequisition')
    op.drop_table('manpowerrequisition')
    # ### end Alembic commands ###
