"""add bd module models

Revision ID: 3339b33718a8
Revises: 0b9ea22ca449
Create Date: 2026-02-14 10:42:15.875193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3339b33718a8'
down_revision: Union[str, None] = '0b9ea22ca449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=False)
    op.create_index(op.f('ix_contact_full_name'), 'contact', ['full_name'], unique=False)
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('NEW', 'QUALIFIED', 'DISCOVERY', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST', name='leadstage'), nullable=False),
    sa.Column('probability_percent', sa.Integer(), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_id'), 'lead', ['id'], unique=False)
    op.create_index(op.f('ix_lead_lead_id'), 'lead', ['lead_id'], unique=True)
    op.create_index(op.f('ix_lead_owner_user_id'), 'lead', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_lead_stage'), 'lead', ['stage'], unique=False)
    op.create_index(op.f('ix_lead_title'), 'lead', ['title'], unique=False)
    op.create_table('bd_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CALL', 'EMAIL', 'MEETING', 'NOTE', name='activitytype'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bd_activity_log_created_by_id'), 'bd_activity_log', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_bd_activity_log_id'), 'bd_activity_log', ['id'], unique=False)
    op.create_index(op.f('ix_bd_activity_log_lead_id'), 'bd_activity_log', ['lead_id'], unique=False)
    op.create_index(op.f('ix_bd_activity_log_type'), 'bd_activity_log', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bd_activity_log_type'), table_name='bd_activity_log')
    op.drop_index(op.f('ix_bd_activity_log_lead_id'), table_name='bd_activity_log')
    op.drop_index(op.f('ix_bd_activity_log_id'), table_name='bd_activity_log')
    op.drop_index(op.f('ix_bd_activity_log_created_by_id'), table_name='bd_activity_log')
    op.drop_table('bd_activity_log')
    op.drop_index(op.f('ix_lead_title'), table_name='lead')
    op.drop_index(op.f('ix_lead_stage'), table_name='lead')
    op.drop_index(op.f('ix_lead_owner_user_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_lead_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_full_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
