"""add assigned_user_id to estimate phase

Revision ID: 3762f48584f9
Revises: 2c4204d5b2af
Create Date: 2026-02-16 07:04:51.111347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3762f48584f9'
down_revision: Union[str, None] = '2c4204d5b2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimatephase', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estimatephase', 'user', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estimatephase', type_='foreignkey')
    op.drop_column('estimatephase', 'assigned_user_id')
    # ### end Alembic commands ###
