"""re-add timesheet tables with accumulated_seconds

Revision ID: 71ff5cea1fe6
Revises: 276236fd2e6e
Create Date: 2026-02-11 12:20:04.768628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ff5cea1fe6'
down_revision: Union[str, None] = '276236fd2e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS timeentry")
    op.create_table('timeentry',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=True),
        sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('duration_seconds', sa.Integer(), nullable=False),
        sa.Column('source', sa.Enum('TIMER', 'MANUAL', name='timeentrysource'), nullable=False),
        sa.Column('manual_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeentry_id'), 'timeentry', ['id'], unique=False)
    op.create_index(op.f('ix_timeentry_project_id'), 'timeentry', ['project_id'], unique=False)
    op.create_index(op.f('ix_timeentry_task_id'), 'timeentry', ['task_id'], unique=False)
    op.create_index(op.f('ix_timeentry_user_id'), 'timeentry', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeentry_user_id'), table_name='timeentry')
    op.drop_index(op.f('ix_timeentry_task_id'), table_name='timeentry')
    op.drop_index(op.f('ix_timeentry_project_id'), table_name='timeentry')
    op.drop_index(op.f('ix_timeentry_id'), table_name='timeentry')
    op.drop_table('timeentry')
    # ### end Alembic commands ###
