"""Add interview_type to Interview

Revision ID: 893a976f1056
Revises: 60d30fe066e8
Create Date: 2026-02-16 10:05:26.635446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893a976f1056'
down_revision: Union[str, None] = '60d30fe066e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('interview_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview', 'interview_type')
    # ### end Alembic commands ###
