"""Add notes to Interview

Revision ID: 907aecdffdec
Revises: 893a976f1056
Create Date: 2026-02-16 10:18:51.001612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907aecdffdec'
down_revision: Union[str, None] = '893a976f1056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview', 'notes')
    # ### end Alembic commands ###
