"""add estimate models

Revision ID: ad3ab7b15780
Revises: 2744776c1c81
Create Date: 2026-02-14 11:23:21.703644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3ab7b15780'
down_revision: Union[str, None] = '2744776c1c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimateversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'ARCHIVED', name='estimatestatus'), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('scope_included', sa.Text(), nullable=True),
    sa.Column('scope_excluded', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('total_cost_decimal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contingency_percent', sa.Float(), nullable=False),
    sa.Column('margin_percent', sa.Float(), nullable=False),
    sa.Column('total_price_decimal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimateversion_created_by_id'), 'estimateversion', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_estimateversion_id'), 'estimateversion', ['id'], unique=False)
    op.create_index(op.f('ix_estimateversion_lead_id'), 'estimateversion', ['lead_id'], unique=False)
    op.create_index(op.f('ix_estimateversion_status'), 'estimateversion', ['status'], unique=False)
    op.create_table('estimatephase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('phase_name', sa.String(length=100), nullable=False),
    sa.Column('start_offset_days', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['estimateversion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimatephase_id'), 'estimatephase', ['id'], unique=False)
    op.create_index(op.f('ix_estimatephase_version_id'), 'estimatephase', ['version_id'], unique=False)
    op.create_table('estimateresourceline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('cost_decimal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['estimateversion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimateresourceline_id'), 'estimateresourceline', ['id'], unique=False)
    op.create_index(op.f('ix_estimateresourceline_version_id'), 'estimateresourceline', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimateresourceline_version_id'), table_name='estimateresourceline')
    op.drop_index(op.f('ix_estimateresourceline_id'), table_name='estimateresourceline')
    op.drop_table('estimateresourceline')
    op.drop_index(op.f('ix_estimatephase_version_id'), table_name='estimatephase')
    op.drop_index(op.f('ix_estimatephase_id'), table_name='estimatephase')
    op.drop_table('estimatephase')
    op.drop_index(op.f('ix_estimateversion_status'), table_name='estimateversion')
    op.drop_index(op.f('ix_estimateversion_lead_id'), table_name='estimateversion')
    op.drop_index(op.f('ix_estimateversion_id'), table_name='estimateversion')
    op.drop_index(op.f('ix_estimateversion_created_by_id'), table_name='estimateversion')
    op.drop_table('estimateversion')
    # ### end Alembic commands ###
