"""add_employee_model

Revision ID: b7239791cac0
Revises: 0b659cc8b6ce
Create Date: 2026-02-12 05:06:00.742828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7239791cac0'
down_revision: Union[str, None] = '0b659cc8b6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('pf_number', sa.String(length=50), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_department'), 'employee', ['department'], unique=False)
    op.create_index(op.f('ix_employee_designation'), 'employee', ['designation'], unique=False)
    op.create_index(op.f('ix_employee_employee_id'), 'employee', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_index(op.f('ix_employee_status'), 'employee', ['status'], unique=False)
    op.create_index(op.f('ix_employee_user_id'), 'employee', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_user_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_status'), table_name='employee')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_employee_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_designation'), table_name='employee')
    op.drop_index(op.f('ix_employee_department'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
