"""add_leave_and_approval_models

Revision ID: ed6e5a79e5c2
Revises: 71ff5cea1fe6
Create Date: 2026-02-11 15:57:04.604984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6e5a79e5c2'
down_revision: Union[str, None] = '71ff5cea1fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvalitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('current_step_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvalitem_id'), 'approvalitem', ['id'], unique=False)
    op.create_index(op.f('ix_approvalitem_resource_id'), 'approvalitem', ['resource_id'], unique=False)
    op.create_index(op.f('ix_approvalitem_resource_type'), 'approvalitem', ['resource_type'], unique=False)
    op.create_index(op.f('ix_approvalitem_status'), 'approvalitem', ['status'], unique=False)
    op.create_table('leavetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('unpaid_allowed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leavetype_id'), 'leavetype', ['id'], unique=False)
    op.create_index(op.f('ix_leavetype_name'), 'leavetype', ['name'], unique=True)
    op.create_table('approvalstep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_item_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_item_id'], ['approvalitem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvalstep_approval_item_id'), 'approvalstep', ['approval_item_id'], unique=False)
    op.create_index(op.f('ix_approvalstep_id'), 'approvalstep', ['id'], unique=False)
    op.create_table('leavebalanceledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leavetype.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leavebalanceledger_id'), 'leavebalanceledger', ['id'], unique=False)
    op.create_index(op.f('ix_leavebalanceledger_leave_type_id'), 'leavebalanceledger', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leavebalanceledger_user_id'), 'leavebalanceledger', ['user_id'], unique=False)
    op.create_table('leaverequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_half_day', sa.Boolean(), nullable=False),
    sa.Column('half_day_session', sa.Enum('MORNING', 'AFTERNOON', name='halfdaysession'), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leavetype.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaverequest_employee_id'), 'leaverequest', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leaverequest_id'), 'leaverequest', ['id'], unique=False)
    op.create_index(op.f('ix_leaverequest_leave_type_id'), 'leaverequest', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leaverequest_status'), 'leaverequest', ['status'], unique=False)
    op.add_column('user', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'manager_id')
    op.drop_index(op.f('ix_leaverequest_status'), table_name='leaverequest')
    op.drop_index(op.f('ix_leaverequest_leave_type_id'), table_name='leaverequest')
    op.drop_index(op.f('ix_leaverequest_id'), table_name='leaverequest')
    op.drop_index(op.f('ix_leaverequest_employee_id'), table_name='leaverequest')
    op.drop_table('leaverequest')
    op.drop_index(op.f('ix_leavebalanceledger_user_id'), table_name='leavebalanceledger')
    op.drop_index(op.f('ix_leavebalanceledger_leave_type_id'), table_name='leavebalanceledger')
    op.drop_index(op.f('ix_leavebalanceledger_id'), table_name='leavebalanceledger')
    op.drop_table('leavebalanceledger')
    op.drop_index(op.f('ix_approvalstep_id'), table_name='approvalstep')
    op.drop_index(op.f('ix_approvalstep_approval_item_id'), table_name='approvalstep')
    op.drop_table('approvalstep')
    op.drop_index(op.f('ix_leavetype_name'), table_name='leavetype')
    op.drop_index(op.f('ix_leavetype_id'), table_name='leavetype')
    op.drop_table('leavetype')
    op.drop_index(op.f('ix_approvalitem_status'), table_name='approvalitem')
    op.drop_index(op.f('ix_approvalitem_resource_type'), table_name='approvalitem')
    op.drop_index(op.f('ix_approvalitem_resource_id'), table_name='approvalitem')
    op.drop_index(op.f('ix_approvalitem_id'), table_name='approvalitem')
    op.drop_table('approvalitem')
    # ### end Alembic commands ###
