"""add_time_entry_table

Revision ID: efae53888a25
Revises: 01e0a6b513ac
Create Date: 2026-02-11 05:35:02.693049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efae53888a25'
down_revision: Union[str, None] = '01e0a6b513ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_action_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accumulated_duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeentry_id'), 'timeentry', ['id'], unique=False)
    op.create_index(op.f('ix_timeentry_status'), 'timeentry', ['status'], unique=False)
    op.create_index(op.f('ix_timeentry_user_id'), 'timeentry', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeentry_user_id'), table_name='timeentry')
    op.drop_index(op.f('ix_timeentry_status'), table_name='timeentry')
    op.drop_index(op.f('ix_timeentry_id'), table_name='timeentry')
    op.drop_table('timeentry')
    # ### end Alembic commands ###
