"""add comp_off_accrual table

Stores comp-off requests auto-generated by the punch-out flow when an
employee worked >=6.5h on a company holiday. Status transitions are driven
by the existing ApprovalItem workflow (resource_type='comp_off_accrual').
On final HR approval, +days_credited is added to the CO LeaveBalanceLedger.

Revision ID: v3q4r5s6t7u8
Revises: u2p3q4r5s6t7
Create Date: 2026-04-30
"""
from alembic import op
import sqlalchemy as sa

revision = "v3q4r5s6t7u8"
down_revision = "u2p3q4r5s6t7"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "comp_off_accrual",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "user_id", sa.Integer(),
            sa.ForeignKey("user.id", ondelete="CASCADE"),
            nullable=False, index=True,
        ),
        sa.Column("holiday_date", sa.Date(), nullable=False, index=True),
        sa.Column("holiday_name", sa.String(100), nullable=True),
        sa.Column(
            "attendance_id", sa.Integer(),
            sa.ForeignKey("attendance.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("worked_minutes", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("days_credited", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("reason", sa.String(500), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            nullable=False, server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "user_id", "holiday_date",
            name="uq_comp_off_accrual_user_holiday",
        ),
    )


def downgrade():
    op.drop_table("comp_off_accrual")
